# -*- coding: utf-8 -*-
"""SM_back.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVvqKCZsvVQ2wDVg4iTg-VXbUvmNoGQK
"""

"""
기기 상태 머신 (Device State Machine)
전이 표 기반 구현
"""

from enum import Enum, auto
from dataclasses import dataclass, field
from typing import Optional, Callable
import sys


# ──────────────────────────────────────────────
# 1. 상태 정의
# ──────────────────────────────────────────────

class State(Enum):
    T1              = "T1: 준비 (기기를 껐다 켜시오)"
    T2              = "T2: 쓰기 중 (고지 마시오 / Error Code)"
    T3_RETRY        = "T3: 검증 (ROM VER CHECK) → Retry 발동"
    T3_NO_RETRY     = "T3: 검증 (ROM VER CHECK) → Retry 미발동"
    FACTORY         = "FACTORY"
    T4              = "T4: 완료 (메뉴 화면)"
    ERROR           = "Error"
    SHUTDOWN        = "Performing Shutdown"


# ──────────────────────────────────────────────
# 2. 이벤트 정의
# ──────────────────────────────────────────────

class Event(Enum):
    POWER_BUTTON    = "전원 버튼 클릭/재클릭"
    BTN_123         = "[123] 버튼 클릭"
    FACTORY_BUTTON  = "FACTORY 버튼 클릭"
    BTN_04          = "04 버튼 클릭"
    ADMIN_RESET     = "관리자 수동 리셋"


# ──────────────────────────────────────────────
# 3. 예외 타입 정의
# ──────────────────────────────────────────────

class ExceptionType(Enum):
    SOFT_ERROR_1    = "Soft Error1"
    SOFT_ERROR_2    = "Soft Error2"
    SOFT_ERROR_3    = "Soft Error3"
    SOFT_ERROR_STAR = "Soft Error* (일시적 응답 없음)"
    HARD_ERROR      = "Hard Error"
    NO_RESPONSE     = "응답 없음"


# ──────────────────────────────────────────────
# 4. 전이 결과
# ──────────────────────────────────────────────

@dataclass
class TransitionResult:
    next_state: State
    message: str
    retry_increment: int = 0
    lock: bool = False


# ──────────────────────────────────────────────
# 5. 상태 머신 클래스
# ──────────────────────────────────────────────

class DeviceStateMachine:

    def __init__(self):
        self.state: State = State.T1
        self.retry_count: int = 0
        self.log: list[str] = []
        self._locked: bool = False

    # ── 로깅 ──────────────────────────────────

    def _log(self, msg: str) -> None:
        self.log.append(msg)
        print(msg)

    def _log_transition(self, prev: State, event_or_exc: str, result: TransitionResult) -> None:
        self._log(
            f"  [{prev.name}] --({event_or_exc})--> [{result.next_state.name}]"
            + (f"  | Retry+{result.retry_increment} (총 {self.retry_count})" if result.retry_increment else "")
            + (f"  | LOCK 발동" if result.lock else "")
        )
        self._log(f"    → {result.message}")

    # ── Guard (정상 전이) ─────────────────────

    def trigger(self, event: Event) -> Optional[TransitionResult]:
        """
        Guard 조건을 통한 정상 이벤트 처리.
        현재 상태에서 해당 이벤트가 허용되면 전이를 수행한다.
        """
        if self._locked:
            self._log("  ⚠ Lock 상태입니다. 이벤트를 처리할 수 없습니다.")
            return None

        handler = self._GUARD_TABLE.get((self.state, event))
        if handler is None:
            self._log(f"  ✗ [{self.state.name}] 에서 이벤트 [{event.value}]는 허용되지 않습니다.")
            return None

        result = handler(self)
        prev = self.state
        self.retry_count += result.retry_increment
        self._locked = result.lock
        self.state = result.next_state
        self._log_transition(prev, event.value, result)
        return result

    # ── Exception (예외 처리) ─────────────────

    def handle_exception(self, exc_type: ExceptionType) -> Optional[TransitionResult]:
        """
        예외 발생 처리.
        현재 상태와 예외 타입에 따라 전이 또는 유지를 수행한다.
        """
        handler = self._EXCEPTION_TABLE.get((self.state, exc_type))
        if handler is None:
            self._log(f"  ✗ [{self.state.name}] 에서 예외 [{exc_type.value}]에 대한 처리가 없습니다.")
            return None

        result = handler(self)
        prev = self.state
        self.retry_count += result.retry_increment
        self._locked = result.lock
        self.state = result.next_state
        self._log_transition(prev, f"EXC:{exc_type.value}", result)
        return result

    # ── 상태 조회 ─────────────────────────────

    def status(self) -> str:
        return (
            f"  상태     : {self.state.name} — {self.state.value}\n"
            f"  Retry    : {self.retry_count}\n"
            f"  Lock     : {'예' if self._locked else '아니오'}"
        )

    # ──────────────────────────────────────────
    # Guard 전이 핸들러 (정상 경로)
    # ──────────────────────────────────────────

    def _t1_power(self) -> TransitionResult:
        return TransitionResult(
            next_state=State.T2,
            message="전원 리셋 신호 확인 → T2 전이"
        )

    def _t2_btn123(self) -> TransitionResult:
        return TransitionResult(
            next_state=State.T3_RETRY,
            message="Settings 버튼 활성화 신호 → T3 전이"
        )

    def _t3_retry_factory(self) -> TransitionResult:
        # 조기 Retry 카운트 = 0 이 Guard 조건
        if self.retry_count > 0:
            self._log("    (주의) Retry 카운트가 0이 아닙니다. Guard 조건 미충족 가능성.")
        return TransitionResult(
            next_state=State.FACTORY,
            message="FACTORY 버튼 활성화 신호 (조기 Retry 카운트=0) → FACTORY 전이"
        )

    def _t3_no_retry_factory(self) -> TransitionResult:
        return TransitionResult(
            next_state=State.T4,
            message="FACTORY 버튼 활성화 신호 → T4 전이"
        )

    def _factory_btn04(self) -> TransitionResult:
        return TransitionResult(
            next_state=State.T3_RETRY,
            message="04 버튼 활성화 신호 → T3 복귀"
        )

    def _t4_power(self) -> TransitionResult:
        return TransitionResult(
            next_state=State.SHUTDOWN,
            message="전원 리셋 신호 확인 → Performing Shutdown"
        )

    def _error_admin_reset(self) -> TransitionResult:
        self.retry_count = 0
        return TransitionResult(
            next_state=State.T1,
            message="관리자 수동 리셋 → T1 복귀 (자동 복구 없음)"
        )

    # ──────────────────────────────────────────
    # 예외 처리 핸들러
    # ──────────────────────────────────────────

    # T1 예외
    def _t1_soft1(self) -> TransitionResult:
        return TransitionResult(State.T1, "T1 유지 + Retry 안내", retry_increment=1)

    def _t1_soft2(self) -> TransitionResult:
        return TransitionResult(State.T1, "Lock 발동", lock=True)

    def _t1_hard(self) -> TransitionResult:
        return TransitionResult(State.ERROR, "Error 이미지로 강제 전이")

    # T2 예외
    def _t2_soft1(self) -> TransitionResult:
        return TransitionResult(State.T2, "T2 유지 + Retry 안내", retry_increment=1)

    def _t2_soft2(self) -> TransitionResult:
        return TransitionResult(State.T2, "Lock 발동", lock=True)

    def _t2_hard(self) -> TransitionResult:
        return TransitionResult(State.ERROR, "Error 이미지로 강제 전이")

    # T3 (Retry 발동) 예외
    def _t3r_soft1(self) -> TransitionResult:
        return TransitionResult(State.T3_RETRY, "T3 유지 + [Retry 카운트+1] → Retry 안내", retry_increment=1)

    def _t3r_soft3(self) -> TransitionResult:
        return TransitionResult(State.FACTORY, "FACTORY 이동 + [Retry 카운트+1] → Retry 안내", retry_increment=1)

    # T3 (Retry 미발동) 예외
    def _t3n_soft2(self) -> TransitionResult:
        return TransitionResult(State.T3_NO_RETRY, "Lock 발동", lock=True)

    def _t3n_hard(self) -> TransitionResult:
        return TransitionResult(State.ERROR, "Error 이미지로 강제 전이")

    # FACTORY 예외
    def _fac_soft1(self) -> TransitionResult:
        return TransitionResult(State.FACTORY, "FACTORY 유지 + [Retry 카운트+1] → Retry 안내", retry_increment=1)

    def _fac_soft2(self) -> TransitionResult:
        return TransitionResult(State.FACTORY, "Lock 발동", lock=True)

    def _fac_soft_star(self) -> TransitionResult:
        return TransitionResult(
            State.T3_RETRY,
            "일시적 응답 없음 → PREV 발동 → T3 복귀 + [Retry+1]",
            retry_increment=1
        )

    def _fac_hard(self) -> TransitionResult:
        return TransitionResult(State.ERROR, "Error 이미지로 강제 전이")

    # T4 예외
    def _t4_no_response(self) -> TransitionResult:
        return TransitionResult(State.T4, "T4 유지 + Retry 안내", retry_increment=1)

    def _t4_soft2(self) -> TransitionResult:
        return TransitionResult(State.T4, "Lock 발동", lock=True)

    def _t4_hard(self) -> TransitionResult:
        return TransitionResult(State.ERROR, "Error 이미지로 강제 전이")

    # ──────────────────────────────────────────
    # Lookup 테이블 (상태 × 이벤트/예외 → 핸들러)
    # ──────────────────────────────────────────

    _GUARD_TABLE: dict = {}      # 클래스 선언 후 초기화
    _EXCEPTION_TABLE: dict = {}


# 클래스 정의 후 테이블 초기화
DeviceStateMachine._GUARD_TABLE = {
    (State.T1,          Event.POWER_BUTTON):   DeviceStateMachine._t1_power,
    (State.T2,          Event.BTN_123):        DeviceStateMachine._t2_btn123,
    (State.T3_RETRY,    Event.FACTORY_BUTTON): DeviceStateMachine._t3_retry_factory,
    (State.T3_NO_RETRY, Event.FACTORY_BUTTON): DeviceStateMachine._t3_no_retry_factory,
    (State.FACTORY,     Event.BTN_04):         DeviceStateMachine._factory_btn04,
    (State.T4,          Event.POWER_BUTTON):   DeviceStateMachine._t4_power,
    (State.ERROR,       Event.ADMIN_RESET):    DeviceStateMachine._error_admin_reset,
}

DeviceStateMachine._EXCEPTION_TABLE = {
    # T1
    (State.T1, ExceptionType.SOFT_ERROR_1): DeviceStateMachine._t1_soft1,
    (State.T1, ExceptionType.SOFT_ERROR_2): DeviceStateMachine._t1_soft2,
    (State.T1, ExceptionType.HARD_ERROR):   DeviceStateMachine._t1_hard,
    # T2
    (State.T2, ExceptionType.SOFT_ERROR_1): DeviceStateMachine._t2_soft1,
    (State.T2, ExceptionType.SOFT_ERROR_2): DeviceStateMachine._t2_soft2,
    (State.T2, ExceptionType.HARD_ERROR):   DeviceStateMachine._t2_hard,
    # T3 Retry
    (State.T3_RETRY, ExceptionType.SOFT_ERROR_1): DeviceStateMachine._t3r_soft1,
    (State.T3_RETRY, ExceptionType.SOFT_ERROR_3): DeviceStateMachine._t3r_soft3,
    # T3 No-Retry
    (State.T3_NO_RETRY, ExceptionType.SOFT_ERROR_2): DeviceStateMachine._t3n_soft2,
    (State.T3_NO_RETRY, ExceptionType.HARD_ERROR):   DeviceStateMachine._t3n_hard,
    # FACTORY
    (State.FACTORY, ExceptionType.SOFT_ERROR_1):   DeviceStateMachine._fac_soft1,
    (State.FACTORY, ExceptionType.SOFT_ERROR_2):   DeviceStateMachine._fac_soft2,
    (State.FACTORY, ExceptionType.SOFT_ERROR_STAR):DeviceStateMachine._fac_soft_star,
    (State.FACTORY, ExceptionType.HARD_ERROR):     DeviceStateMachine._fac_hard,
    # T4
    (State.T4, ExceptionType.NO_RESPONSE):  DeviceStateMachine._t4_no_response,
    (State.T4, ExceptionType.SOFT_ERROR_2): DeviceStateMachine._t4_soft2,
    (State.T4, ExceptionType.HARD_ERROR):   DeviceStateMachine._t4_hard,
}


# ──────────────────────────────────────────────
# 6. CLI 인터랙티브 모드
# ──────────────────────────────────────────────

def interactive_mode():
    sm = DeviceStateMachine()

    print("=" * 58)
    print("  기기 상태 머신 시뮬레이터")
    print("=" * 58)

    EVENTS = list(Event)
    EXCEPTIONS = list(ExceptionType)

    while True:
        print()
        print(sm.status())
        print()
        print("  [이벤트]")
        for i, e in enumerate(EVENTS, 1):
            print(f"    {i}. {e.value}")
        print()
        print("  [예외]")
        for i, exc in enumerate(EXCEPTIONS, 1):
            print(f"    {len(EVENTS)+i}. EXC: {exc.value}")
        print()
        print("  [기타]  q=종료  r=리셋  s=상태 재출력")
        print("-" * 58)

        choice = input("  선택 > ").strip().lower()

        if choice == 'q':
            print("\n  종료합니다.")
            break
        elif choice == 'r':
            sm = DeviceStateMachine()
            print("\n  머신을 초기화했습니다.")
        elif choice == 's':
            continue
        elif choice.isdigit():
            idx = int(choice)
            if 1 <= idx <= len(EVENTS):
                evt = EVENTS[idx - 1]
                print(f"\n  ▶ 이벤트 발동: {evt.value}")
                sm.trigger(evt)
            elif len(EVENTS) < idx <= len(EVENTS) + len(EXCEPTIONS):
                exc = EXCEPTIONS[idx - len(EVENTS) - 1]
                print(f"\n  ⚡ 예외 발동: {exc.value}")
                sm.handle_exception(exc)
            else:
                print("  잘못된 번호입니다.")
        else:
            print("  알 수 없는 입력입니다.")


# ──────────────────────────────────────────────
# 7. 자동 시나리오 테스트
# ──────────────────────────────────────────────

def run_scenario():
    """정상 흐름 + 예외 흐름 시나리오 자동 실행"""
    print("=" * 58)
    print("  시나리오 테스트")
    print("=" * 58)

    sm = DeviceStateMachine()

    steps = [
        ("정상 전이: T1 → T2",          lambda: sm.trigger(Event.POWER_BUTTON)),
        ("예외: T2 Soft Error1 (유지)",   lambda: sm.handle_exception(ExceptionType.SOFT_ERROR_1)),
        ("정상 전이: T2 → T3",           lambda: sm.trigger(Event.BTN_123)),
        ("예외: T3 Soft Error1 (유지)",   lambda: sm.handle_exception(ExceptionType.SOFT_ERROR_1)),
        ("정상 전이: T3 → FACTORY",      lambda: sm.trigger(Event.FACTORY_BUTTON)),
        ("예외: FACTORY Soft Error*",     lambda: sm.handle_exception(ExceptionType.SOFT_ERROR_STAR)),
        ("정상 전이: T3 → FACTORY",      lambda: sm.trigger(Event.FACTORY_BUTTON)),
        ("정상 전이: FACTORY → T3",      lambda: sm.trigger(Event.BTN_04)),
        # T3_RETRY → T3_NO_RETRY 로 강제 이동 후 T4 진행
        ("강제 상태 변경: T3_NO_RETRY",   lambda: setattr(sm, 'state', State.T3_NO_RETRY) or None),
        ("정상 전이: T3 → T4",           lambda: sm.trigger(Event.FACTORY_BUTTON)),
        ("예외: T4 Hard Error",           lambda: sm.handle_exception(ExceptionType.HARD_ERROR)),
        ("관리자 리셋: ERROR → T1",       lambda: sm.trigger(Event.ADMIN_RESET)),
    ]

    for desc, fn in steps:
        print(f"\n>>> {desc}")
        fn()

    print()
    print("=" * 58)
    print("  최종 상태:")
    print(sm.status())
    print("=" * 58)


# ──────────────────────────────────────────────
# 8. 진입점
# ──────────────────────────────────────────────

if __name__ == "__main__":
    if "--scenario" in sys.argv:
        run_scenario()
    else:
        interactive_mode()